plugins { id 'com.android.application' }
android {
    namespace 'com.saral.morghban'
    compileSdk 35
    defaultConfig {
        applicationId "com.saral.morghban"
        minSdk 24
        targetSdk 35
        versionCode 3
        versionName "1.2"
    }
}

dependencies { implementation 'androidx.webkit:webkit:1.17.1' }
